services:
  m4: 
    build:
      context: app
      target: builder
    ports: 
      - '8000:8000'
    volumes:
      - code_data:/code
      - .:/local:rw

volumes:
  code_data:
    driver: local

networks:
  frontend:
  backend:
