services:
  m4:
    image: ${DOCKER_REGISTRY}/totolo-m4
    build:
      context: .
      dockerfile: ./m4/Dockerfile
    hostname: totolo-m4
    networks:
      - backend
      - frontend
    volumes:
      - ../..:/local/tstp:rw
      - code_data:/code
      - www_data:/www/pub
    ports:
      - "8000:8000"
      - "8001:8001"

  sphinx:
    image: ${DOCKER_REGISTRY}/totolo-sphinx
    build:
      context: .
      dockerfile: ./sphinx/Dockerfile
    networks:
      - backend
    hostname: totolo-sphinx
    ports:
    - "9312:9312"
    - "9306:9306"
    volumes:
     - sphinx_code:/opt/sphinx
    mem_limit: 256m

volumes:
  sphinx_data:
    driver: local
  sphinx_code:
    driver: local
  code_data:
    driver: local
  www_data:
    driver: local

networks:
  frontend:
  backend:
