services:
  m4:
    build:
      context: .
      dockerfile: ./m4/Dockerfile
    image: tstp/m4:latest
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - code_data:/code
      - www_data:/www/pub
    secrets:
      - pycredentials

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: es01
    command: ["elasticsearch", "-Elogger.level=WARN"]
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend

volumes:
  es_data:
    driver: local
  code_data:
    driver: local
  www_data:
    driver: local

networks:
  frontend:
  backend:

secrets:
  pycredentials:
    file: credentials.py
