services:
  m4:
    image: ${DOCKER_REGISTRY}/totolo-m4
    build:
      context: .
      dockerfile: ./m4/Dockerfile
    networks:
      - backend
    volumes:
      - ../..:/local/tstp:rw
      - code_data:/code
      - www_data:/www/pub
    ports:
      - "8000:8000"
      - "8001:8001"

  es:
    image: ${DOCKER_REGISTRY}/totolo-es
    build:
      context: .
      dockerfile: ./es/Dockerfile
    container_name: es
    command: ["elasticsearch", "-Elogger.level=WARN"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M

volumes:
  es_data:
    driver: local
  code_data:
    driver: local
  www_data:
    driver: local

networks:
  frontend:
  backend:
