# Generated by Django 3.2.16 on 2022-12-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Score')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('parents', models.TextField(verbose_name='Parents')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
