# Generated by Django 3.2.13 on 2023-01-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={},
        ),
        migrations.RemoveField(
            model_name='theme',
            name='score',
        ),
        migrations.AddField(
            model_name='theme',
            name='children',
            field=models.TextField(default='', verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='parents',
            field=models.TextField(default='', verbose_name='Parents'),
        ),
    ]
