# Generated by Django 3.2.13 on 2023-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0003_auto_20230115_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.CharField(default='', max_length=32, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
