# Generated by Django 3.2.13 on 2023-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0004_auto_20230116_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=255, verbose_name='sid')),
                ('theme', models.TextField(default='', verbose_name='Theme')),
                ('weight', models.CharField(default='', max_length=16, verbose_name='Weight')),
                ('motivation', models.TextField(default='', verbose_name='Motivation')),
                ('capacity', models.TextField(default='', verbose_name='Capacity')),
                ('notes', models.TextField(default='', verbose_name='Notes')),
            ],
        ),
    ]
