# Generated by Django 3.2.13 on 2023-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0005_storytheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sid',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='sid'),
        ),
        migrations.AlterField(
            model_name='storytheme',
            name='sid',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='sid'),
        ),
        migrations.AlterField(
            model_name='storytheme',
            name='theme',
            field=models.TextField(db_index=True, default='', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
