# Generated by Django 3.2.13 on 2023-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0006_auto_20230116_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storytheme',
            name='id',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='id',
        ),
        migrations.AddField(
            model_name='story',
            name='idx',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='idx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storytheme',
            name='idx',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='idx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='idx',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='idx'),
            preserve_default=False,
        ),
    ]
