# Generated by Django 3.2.13 on 2023-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0008_auto_20230119_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False, verbose_name='idx')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('timestamp', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='timestamp')),
                ('data', models.BinaryField(default=b'', verbose_name='data')),
            ],
        ),
    ]
