# Generated by Django 3.2.13 on 2023-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0009_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='timestamp',
            field=models.CharField(db_index=True, max_length=32, verbose_name='timestamp'),
        ),
    ]
