# Generated by Django 3.2.13 on 2023-01-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologyexplorer', '0011_auto_20230124_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
    ]
