version: "3.8"
services:
  m4:
    build:
      context: .
      dockerfile: ./m4/Dockerfile
    image: tstp/m4
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - code_data:/code
      - www_data:/www/pub
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=10
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=2
    secrets:
      - pycredentials

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: tstp/php
    depends_on:
      - mysql
      - m4
    networks:
      - backend
    volumes:
      - code_data:/code
      - www_data:/www/pub
    environment:
      - WAIT_HOSTS=m4:31985
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=3
      - WAIT_HOST_CONNECT_TIMEOUT=3

  apache:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    image: tstp/apache
    depends_on:
      - php
    networks:
      - frontend
      - backend
    volumes:
      - code_data:/code
      - www_data:/www/pub
    ports:
      - "80:80"

  mysql:
    image: mysql/mysql-server:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=tstpdockeruser
      - MYSQL_PASSWORD=tstpdockerpass
      - MYSQL_DATABASE=tstpdockerdb

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es01
    command: ["elasticsearch", "-Elogger.level=WARN"]
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend

volumes:
  es_data:
    driver: local
  code_data:
    driver: local
  www_data:
    driver: local

networks:
  frontend:
  backend:

secrets:
  pycredentials:
    file: ../pylib/credentials.py
