version: "3"
services:
  m4:
    image: 777087578287.dkr.ecr.eu-west-2.amazonaws.com/tstp/m4:latest
    networks:
      - backend
    volumes:
      - code_data:/code
      - www_data:/www/pub

volumes:
  es_data:
    driver: local
  code_data:
    driver: local
  www_data:
    driver: local

networks:
  frontend:
  backend:
