version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - ..:/local/tstp:rw
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=3
      - WAIT_HOST_CONNECT_TIMEOUT=3
  apache:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ..:/local/tstp
  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=tstpdockeruser
      - MYSQL_PASSWORD=tstpdockerpass
      - MYSQL_DATABASE=tstpdockerdb
networks:
  frontend:
  backend:
