services:
  tan-ru:
    env_file:
      - ./.env.tr.dev
    volumes:
      - ../..:/local/tstp:rw
    ports:
      - "8000:8000"
      - "8080:80"
      - "443:443"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - AWS_REGION
      - AWS_DEFAULT_REGION=eu-west-1

secrets:
  aws:
    file: "~/.aws"

