services:
  m4:
    image: ${DOCKER_REGISTRY}/totolo-m4
    build:
      context: .
      dockerfile: ./m4/Dockerfile
    networks:
      - backend
      - frontend
    volumes:
      - code_data:/code
      - www_data:/www/pub
    ports:
      - "8000:8000"

  sphinx:
    image: ${DOCKER_REGISTRY}/totolo-sphinx
    build:
      context: .
      dockerfile: ./sphinx/Dockerfile
    networks:
      - backend
    ports:
    - "9306:9306"

  sqldb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=totolo
      - POSTGRES_PASSWORD=totolo
      - POSTGRES_DB=totolo_db
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes: 
      - sqldb_data:/var/lib/postgresql/data

volumes:
  sqldb_data:
    driver: local
  sphinx_data:
    driver: local
  sphinx_code:
    driver: local
  code_data:
    driver: local
  www_data:
    driver: local

networks:
  frontend:
  backend:
