version: '3'

services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web
    networks:
      - backend
      - frontend

  mysql:
    image: mysql/mysql-server:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=tstpdockeruser
      - MYSQL_PASSWORD=tstpdockerpass
      - MYSQL_DATABASE=tstpdockerdb
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: eu-west-2
        awslogs-stream-prefix: mysql

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - cluster.name=es01
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend
      - frontend
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: eu-west-2
        awslogs-stream-prefix: mysql

networks:
  frontend:
  backend:

volumes:
  es_data:
  code_data:
  www_data:


